apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: greetings
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: greeting
              image: busybox
              imagePullPolicy: IfNotPresent
              args:
                - /bin/sh
                - -c
                - date; echo Hello from Minikube
          restartPolicy: OnFailure
