apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  namespace: test
  labels:
    app: ubuntu
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
        - name: ubuntu
          image: ubuntu:18.04
          command:
            - /bin/bash
            - -c
            - sleep infinity
          ports:
            - containerPort: 80