version: "3.7"
services:
  postgresql:
    environment:
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bitbrew
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pgnet
    container_name: postgresql
    image: postgres:12-alpine
volumes:
  pgdata:
networks:
  pgnet:
