apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aerospike
  labels:
    app: aerospike
spec:
  replicas: 1
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: aerospike
  serviceName: aerospike-headless
  template:
    metadata:
      labels:
        app: aerospike
    spec:
      containers:
        - image: aerospike/aerospike-server
          name: aerospike
          volumeMounts:
            - name: config
              mountPath: /etc/aerospike
          ports:
            - containerPort: 3000
              name: service
            - containerPort: 3001
              name: fabric
            - containerPort: 3002
              name: mesh-heartbeat
            - containerPort: 3003
              name: info
      volumes:
        - name: config
          configMap:
            name: aerospike-config
            items:
              - key: aerospike.conf
                path: aerospike.conf
