apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aerospike-ebs
  labels:
    app: aerospike
    component: sc
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
